### ISSUE TITLE
HTTP palette examples result in duplicate Objects

### ISSUE THREAD

**Issue by seanmkauffman** [liflab/beepbeep-3-examples#8]
Running PushLocalSimple, I see the following printed to the console:
```
foo,foo,bar,bar,
```
Further experimentation seems to demonstrate that any Object transmitted using HttpDownstreamGateway and HttpUpstreamGateway is being duplicated.  I was able to duplicate the issue using both from the same process and from different processes.  I have not tested other JDKs.

 $ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (IcedTea 3.15.0) (Gentoo icedtea-3.15.0)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by sylvainhalle** [comment]
I fixed the bug in `HttpUpstreamGateway` and updated `http.jar` in the latest release on the palettes repository.
