### ISSUE TITLE
 ca.uqac.lif.cep.ltl no longer there ?

### ISSUE THREAD

**Issue by ghost** [liflab/beepbeep-3-examples#9]
Working on `Version 0.10.3`, I was trying to run LTL examples. 
Many thanks!

**Comment by sylvainhalle** [comment]
Hi! To run some of the examples, you'll need extensions to BeepBeep called _palettes_. The core palettes can be downloaded from here: https://github.com/liflab/beepbeep-3-palettes/releases. Just add them to your classpath and you should be good to go.
